### ISSUE TITLE
ARI scans over different energies

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/sirepo-bluesky#93]
#70 adds support for tweaking the undulator parameters to change the photon energy (currently tested with the Single Spectrum report for the `00000003` simulation).

### TODOs
- For Undulator:
  - [ ] Create an Energy pseudo-axis (calculated from vertical magnetic field component)
  - [ ] Create a Harmonic pseudo-axis to change harmonics for scans
- For PGM:
  - [ ] Create PGM Energy pseudo-axis.
  - [ ] Change the grazing angle in the M2 mirror with photon energy: 
    ![image](https://user-images.githubusercontent.com/13209176/198707424-92428a20-3cb2-443f-a3d2-88bf8bc87157.png)
  - [ ] Change the grazing angle for the grating:
    ![image](https://user-images.githubusercontent.com/13209176/198708170-395fb20b-b3bd-4c05-8dce-febff84e1588.png)
  - [ ] Change gratings (involves changing parameters)
    ![image](https://user-images.githubusercontent.com/13209176/198709086-c70c1d84-390a-4003-b3b4-834977eca191.png)
- [ ] Combined Energy axis

**Comment by mrakitin** [comment]
This issue belongs to the https://github.com/NSLS-II-ARI/profile_sirepo_ari repo. Transferring it from https://github.com/NSLS-II/sirepo-bluesky/issues/93.

**Comment by mrakitin** [comment]
Ah, can't move it across the orgs.

**Comment by mrakitin** [comment]
Reposted at https://github.com/NSLS-II-ARI/profile_sirepo_ari/issues/7.
